// <auto-generated />
namespace SurveyApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class migration41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration41));
        
        string IMigrationMetadata.Id
        {
            get { return "201311021722112_migration41"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
