// <auto-generated />
namespace SurveyApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class migration5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration5));
        
        string IMigrationMetadata.Id
        {
            get { return "201311120906024_migration5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
