// <auto-generated />
namespace SurveyApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class migration2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration2));
        
        string IMigrationMetadata.Id
        {
            get { return "201311192050390_migration2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
